fix(runtime): use object mapper to convert to map
camunda/connector-sdk pull request #146
Opened 2022-10-04 15:56 UTC by menski

## Description

To support POJO responses of the connector function use the jackson object mapper to ensure that response can be casted to a map.

## Related issues

closes #135

2022-10-04 17:21 UTC, nikku commented on runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapper.java
> +  public static final TypeReference<Map<String, Object>> MAP_TYPE_REFERENCE =
Why shall this be public?

2022-10-04 17:22 UTC, nikku commented on runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandlerTest.java
> +      final String resultExpression = "{\"processedOutput\": response.value }";
We could also assert that we do not choke on `FEEL expression -> = response`.

2022-10-04 17:26 UTC, nikku requested changes
Proposal: As we touch this let us go the extra mile and cover all possible cases, at best gracefully:

```
= result
= result.body
```

Still need to gracefully intercept mapping of scalar types:

```
= result.body.someString
```

Cf. https://github.com/camunda/connector-sdk/issues/145#issue-1396257553

2022-10-04 18:13 UTC, igpetrov commented on runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandlerTest.java
> +      // Response from service -> {"callStatus":{"statusCode":"200 OK"}}
```suggestion
      // Response from service -> POJO-object
```

2022-10-04 20:10 UTC, nikku commented
@menski Please checkout https://github.com/camunda/connector-sdk/pull/148 where I implemented variable mappings + improved error messages in the mentioned cases.

2022-10-05 05:50 UTC, tmetzke commented
Thanks a lot for noticing and fixing this, @menski !! One thing that came to my mind here: shouldn't we also convert POJOs for the result variable case? Right now, we're just handling the result expression use case. Do we need to serialize and deserialize the connector result? Does that make sense? This is what happens in the SaaS setup, right?

2022-10-05 06:54 UTC, nikku commented on runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapper.java
> +  public static final TypeReference<Map<String, Object>> MAP_TYPE_REFERENCE =
Fixed via https://github.com/camunda/connector-sdk/pull/146/commits/61fbbaa49d2f6a57beab969d423bff3155fa23ea.

2022-10-05 06:58 UTC, nikku commented
> One thing that came to my mind here: shouldn't we also convert POJOs for the result variable case? Right now, we're just handling the result expression use case.

@tmetzke Variables passed to the Job completion command will be serialized to JSON using a built-in object mapper. Thus I don't believe this is an issue.

2022-10-05 06:59 UTC, nikku approved these changes
Added https://github.com/camunda/connector-sdk/pull/146/commits/85b663fb95087a67c22563f6979abc6dee9fb96d as a dedicated test for the FEEL engine wrapper.

Let's handle everything else as a follow-up.

2022-10-05 07:00 UTC, nikku commented
General observation: Our tests can get an overhaul / improved naming / structure. To be handled outside of this PR.

2022-10-05 07:00 UTC, merged

2022-10-05 07:39 UTC, nikku commented on runtime-job-worker/src/test/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandlerTest.java
> +      // Response from service -> {"callStatus":{"statusCode":"200 OK"}}
Relatest to https://github.com/camunda/connector-sdk/pull/146#issuecomment-1268029311.

I'll take this clean-up as a follow up, as the dust settles.