First draft for simplified object mapping
camunda/connector-sdk pull request #501
Opened 2023-06-29 09:40 UTC by sbuettner

First draft for simplified object mapping and secret handling.

## Description

The idea is to unify json mapping, secret replacement and validation.

## Related issues

relates to camunda/team-connectors/issues/392

2023-06-29 10:51 UTC, markfarkas-camunda requested changes
For me tests in OutboundConnectorContextTest.java are failing. Could you please check those?

2023-06-29 10:55 UTC, igpetrov commented on core/src/main/java/io/camunda/connector/api/annotation/Secret.java
> +@Deprecated(forRemoval = true)
Suggestion: let's also add a javadoc for deprecation note to avoid confusion from external contributors like "ok, I see it's deprecated, what should I use instead?".

2023-06-29 10:57 UTC, chillleader reviewed
I like the direction 👍 `bindVariables` is much simpler and probably more intuitive. But I think we should also keep some lower-level data access methods, e.g. `OutboundConnectorContext::asJson`.

Are you planning to do the same for inbound connectors by introducing the `bindProperties` method in `InboundConnectorContext`?

2023-06-29 10:57 UTC, chillleader commented on core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
> -                        + " via SPI"));
Why not keep the default SPI discovery for validation provider?
I assume we want to use the Spring context, but given that successors can access the field directly, do we need this method at all?

2023-06-29 10:57 UTC, chillleader commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  Map<String, String> getCustomHeaders();
Was it deleted on purpose? Looks like this is not related to variable binding.

2023-06-29 10:57 UTC, chillleader commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
>    void validate(Object input);
This method is also going to be deleted, right?

2023-06-29 10:58 UTC, igpetrov commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  Map<String, String> getCustomHeaders();
This was a request from one of the customers at some point. They added custom task headers and wanted to get those from the context.

2023-06-29 10:58 UTC, igpetrov commented on core/src/main/java/io/camunda/connector/api/secret/SecretContainerHandler.java
> +@Deprecated(forRemoval = true)
Same here. Let's leave a deprecation notice why it's deprecated and what to do instead.

2023-06-29 13:22 UTC, sbuettner commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  Map<String, String> getCustomHeaders();
I just removed things that werent used anywhere.

2023-06-29 13:23 UTC, sbuettner commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  Map<String, String> getCustomHeaders();
Good catch. This was unclear as no connector used it on our side.

2023-06-29 14:11 UTC, sbuettner commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  Map<String, String> getCustomHeaders();
But as @igpetrov said, apparently this is requests. Will bring it back :)

2023-06-29 14:19 UTC, igpetrov commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  Map<String, String> getCustomHeaders();
Yep, see this one https://github.com/camunda/connector-sdk/issues/247

2023-06-30 13:06 UTC, chillleader commented on core/src/main/java/io/camunda/connector/api/outbound/OutboundConnectorContext.java
> -  String asJson();
I'd be a bit hesitant to delete this. There's a chance someone is using this method 🙂

2023-06-30 13:06 UTC, chillleader commented on core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
> +    this.validationProvider = validationProvider;
nit: for consistency, we can also check if `validationProvider` is null, similarly to `secretProvider`

2023-07-03 07:00 UTC, sbuettner commented on core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
> +    this.validationProvider = validationProvider;
@chillleader The idea was to make it optional. WDYT?

2023-07-03 07:01 UTC, sbuettner commented
@igpetrov @markfarkas-camunda @chillleader Please take another look.

2023-07-03 07:39 UTC, sbuettner commented on core/pom.xml
> +    </dependency>
@chillleader Thinking about this one: Should we maybe keep it as a dependency so users can use jackson annotations in their request model classes? This would indicate that its always the default json implementation. WDYT?

2023-07-03 08:03 UTC, chillleader commented on core/pom.xml
> +    </dependency>
Makes sense 👍 I'm thinking that we should maybe add it with the `provided` scope then to avoid version conflicts between connectors and the runtime, WDYT?

2023-07-03 08:08 UTC, chillleader commented on core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
>    protected ValidationProvider getValidationProvider() {
The javadoc for this method needs to be updated:

> By default, SPI is being used and **should be implemented by each implementation**.

This doesn't make sense any more since SPI discovery has been moved to the runtime

2023-07-03 08:11 UTC, chillleader commented on core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
> +    this.validationProvider = validationProvider;
But in case it's not provided, wouldn't it lead to an NPE in `validate` method of this class (which may be relied upon by the ConnectorContext)

2023-07-03 08:14 UTC, sbuettner commented on core/src/main/java/io/camunda/connector/impl/context/AbstractConnectorContext.java
> +    this.validationProvider = validationProvider;
@chillleader I would be fine to make it none-optional then. WDYT?

2023-07-03 10:30 UTC, chillleader approved these changes
Awesome. To summarize the remaining items: we need to update javadocs, and the `validate` method is subject to removal. I'm ok with completing those as follow-ups (e.g. in my upcoming PR about inbound properties).

2023-07-03 11:07 UTC, sbuettner commented
Thank you @chillleader. Any concerns, ideas or approvals from @markfarkas-camunda or @igpetrov ?

2023-07-03 14:19 UTC, igpetrov approved these changes

2023-07-03 14:46 UTC, merged